[build]
  publish = "."

# Custom 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
